default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kurorekishi_me_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: kurorekishi_me_test
  username: root
  password:
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: kurorekishi_me
  password: kurorekishi_me
