development: redis://127.0.0.1:6379/10
test:        redis://127.0.0.1:6379/10
staging:     redis://127.0.0.1:6379/10
production:  redis://kurorekishi-me-2017.23alpb.0001.apne1.cache.amazonaws.com:6379/10
